version: "3.7"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

  flask-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: "postgresql://dronecube:dronecubeapp@db:5432/dronecubedb"
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
      MINIO_URL: "http://minio:9000"
    depends_on:
      - db
      - minio

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: dronecubedb
      POSTGRES_USER: dronecube
      POSTGRES_PASSWORD: dronecubeapp
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    restart: always
    command: server /data
    environment:
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
