version: "3.7"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: dronecubedb
      POSTGRES_USER: dronecube
      POSTGRES_PASSWORD: dronecubeapp
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: drone.cube.reset@gmail.com
      PGADMIN_DEFAULT_PASSWORD: resetpassword123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    networks:
      - pg-network
    depends_on:
      - db

  minio:
    image: minio/minio
    restart: always
    command: server /data
    environment:
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - pg-network

volumes:
  minio_data:

networks:
  pg-network:
